// "use client";
import Link from "next/link";
// import { useRouter } from "next/navigation";
import React from "react";
 export const metadata = {
  title: "Blogs || Next App",
  description: "Generated by create next app",
};

const blogs = [
  {
    id: 1,
    year: 2016,
    title: " title 1",
  },
  {
    id: 2,
    year: 2016,
    title: " title 2",
  },
  {
    id: 3,
    year: 2016,
    title: " title 3",
  },
  {
    id: 4,
    year: 2016,
    title: " title 4",
  },
];

const BlogsPage = () => {
  // const router = useRouter();
  return (
    <div className="container mx-auto p-2 mt-10">
      {blogs.map(({ id, year, title }) => (
        <Link
          className="block border border-blue-600 p-2 my-2"
          href={{
            pathname: `/blogs/${year}/${id}`,
            query: {
              title: title,
            },
          }}
          // onClick={() => router.replace(`/blogs/${year}/${id}?title=${title}`)}
          key={id.id}
        >
          {title}
        </Link>
      ))}
    </div>
  );
};

export default BlogsPage;
