import React from 'react';
export const metadata = {
    title: "AddProduct Next App",
    description: "Generated by create next app",
  };


const AddproDuct = () => {
    return (
        <div>
            <h1>AddProduct</h1>
        </div>
    );
};

export default AddproDuct;