import React from 'react';
export const metadata = {
    title: "ManageProduct || Next App",
    description: "Generated by create next app",
  };


const ManageProduct = () => {
    return (
        <div>
            <h1>ManageProduct</h1>
        </div>
    );
};

export default ManageProduct;