import React from 'react';
export const metadata = {
    title: "AddProduct Next App",
    description: "Generated by create next app",
  };




const AddProduct = () => {
    return (
        <div>
            <h1 className='text-center'>AddProduct</h1>
        </div>
    );
};

export default AddProduct;