import { Roboto } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "400", "500", "700"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Home || Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  console.log("from RootLayout");
  return (
    <html lang="en">
      <body className={`${roboto.variable}font-roboto`}>{children}</body>
    </html>
  );
}
