import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home || Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  console.log("from RootLayout");
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
