import getAllProducts from "@/utils/getAllProducts";
import React from "react";
export const metadata = {
  title: "ManageProduct || Next App",
  description: "Generated by create next app",
};

const ManageProduct = async () => {
  const products = await getAllProducts();

  return (
    <div className="w-full mt-10">
      <h1 className="text-2xl font-semibold mb-5">Manage Products</h1>
      <ManageProduct products={products} />
    </div>
  );
};

export default ManageProduct;
