import React from "react";
export const metadata = {
    title: "DashBoard Next App",
    description: "Generated by create next app",
  };

const DashBoardLayout = ({ children }) => {
  return (
    <div>
      <div>
        <div> SideBar</div>
        {children}
      </div>
    </div>
  );
};

export default DashBoardLayout;
