import React from "react";
import SideBar from "./Sidebar";
export const metadata = {
  title: "DashBoard Next App",
  description: "Generated by create next app",
};

const DashBoardLayout = ({ children }) => {
  return (
    <div>
      <div className="flex container mx-auto">
        <SideBar />
        {children}
      </div>
    </div>
  );
};

export default DashBoardLayout;
